version: '3.8'

services:
  semantic_analyser:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - EMBEDDING_MODEL_NAME=${EMBEDDING_MODEL_NAME}
      - EMBEDDING_MODEL_VARIANT=${EMBEDDING_MODEL_VARIANT}
      - LLM_NAME=${LLM_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      
